### ISSUE TITLE
Bugs cuando se entra en forma local

### ISSUE THREAD

**Issue by jcpy** [jcpy/sfpy#13]
Cuando hago sincronizo el proyecto, salen algunos warnings a la hora cargar productos, tampoco carga la imagen en administrar productos. Yo le calculo que es un problema de permisos del archivo errores_bd.txt. Esto tenemos que prever para cuando el cliente tenga que actualizar su sistema en forma local
![captura de pantalla 2015-02-26 17 25 36](https://cloud.githubusercontent.com/assets/5879372/6401154/0d48aa1a-bddd-11e4-8e53-b01d2904bed4.png)

**Comment by oscardelparaguay** [comment]
ponele 755 a errores_bd.txt
